name: Docker Test
on:
  push:
    branches: [main, dev]
    paths:
      - Dockerfile
  pull_request:
    branches: [main, dev]
    paths:
      - Dockerfile
env:
  DOCKER_IMAGE_TAG: "python-app"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: docker-build
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_TAG }} .

      - name: run-dockle
        uses: erzz/dockle-action@v1

        with:
          image: ${{ env.DOCKER_IMAGE_TAG }}
          exit-code: 1
          failure-threshold: fatal
